language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: QH90/EmXTe5LtyGutnXEeTc/5PCnv7VyNWj1P9HgS97Wvgwnh1pYVnW4olGTv68vrQO3q2KAkqvX6Dzm71UjJbNYor37piGDk+idx29ZH2qLi/nePJ6CCnGTSveJN0l+28gmawTnm1HhPHb169yfjaoXLB9ATXoJp1rYLvHgRi8pj26Gjf+enRKcq/YlTXo7moz0K2oE79mVX3G46CpN8BW7Z1hoNCfbkSG74AHSGh4+nFWG+T3+2o3yJoyTOzqeSHNkiVVz50IOpjiSX4KYM2HQiwdEVpXxOWEaRMGdAMrKS5GcFTUfGmCm0YvIATFbsY3KlTp8FoeGd5ZWTid3ZUVQOR0l/TNmk1ty3iLc0vc4+WpbierExpG4ELjQMYOSTirE/tK/WgqXGlE7ES9x43x5q+oHzuiDPJT+D9qzGhujc/PbhyJ5VtkEoROg2+Kr2FbgkikXC+AUMEBKRAWb4IKidagoPMYy9EZ9lLRpUlRZPvRKZ0nvOkt3P5nN5UHMAWE0eBbmGh7orX0Upff4doRWFHMW4DfE4/01fkjc8tpn8qUqEnXp9G+d3c5IiEBt2llERk7Kqu2aa1e12Wy8STPZZ8HK+HVeX/dJGZVz2oafebqkHY0JhxFQ7T9glJnW1p0dwU3rIXK3SexeHHccnrq+/lVJ+hMfC8GJzI1SE+I=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-patternlab
